// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(everyauth) {
    var addAuth, site, _i, _len, _ref, _results;
    addAuth = function(_arg) {
      var id, secret, service, userId;
      service = _arg.service, id = _arg.id, secret = _arg.secret, userId = _arg.userId;
      if (service === 'twitter') {
        everyauth[service].consumerKey(id).consumerSecret(secret);
      } else {
        everyauth[service].appId(id).appSecret(secret);
      }
      if (service === 'google') {
        everyauth[service].scope('https://www.googleapis.com/auth/userinfo.profile');
      }
      return everyauth[service].findOrCreateUser(function(session, accessToken, accessTokenSecret, data) {
        var user;
        user = data[userId];
        console.log("\n\n" + service + " login, " + user + "\n\n");
        console.log(data);
        console.log("\n\n\n" + service + " login, " + user + "\n\n");
        session.userId = user;
        session.save();
        return true;
      }).redirectPath('/');
    };
    _ref = [
      {
        service: 'facebook',
        id: '414768235235232',
        secret: '5318eadb652e64066aac3caac1f5b923',
        userId: 'username'
      }, {
        service: 'google',
        id: '462948734478-nr4k3hbhhr4t96bt67bfb46hlqan0dpi.apps.googleusercontent.com',
        secret: 'xlKuQy0lR7oyPkgdH2phU_qq',
        userId: 'name'
      }, {
        service: 'github',
        id: '78ce8d91eb2eff1450de',
        secret: 'f2cf4c9f8be62cd3c44c1e604a2893b6690acbe7',
        userId: 'login'
      }, {
        service: 'twitter',
        id: 'zklMWtT9olHJPGlrtFLDDg',
        secret: 'Ft6dWlZHMJ6Qcj9iaf8q33tLMxTtcwmGQLXqQJImpPQ',
        userId: 'screen_name'
      }
    ];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      site = _ref[_i];
      _results.push(addAuth(site));
    }
    return _results;
  };

}).call(this);
